"use client";

import { Download } from "lucide-react";
import { useMemo, useState } from "react";
import AdminSelect from "@/components/admin/AdminSelect";
import DateTimePicker from "@/components/admin/ui/DateTimePicker";
import type { FinanceTransaction } from "@/lib/finance/types";
import type { ServiceRecord } from "@/lib/services/types";
import { dateKey, displayDate, downloadTransactionsCsv, formatMoney } from "./shared";

const METHODS = [{ value: "all", label: "All Methods" }, { value: "cash", label: "Cash" }, { value: "twint", label: "TWINT" }, { value: "card", label: "Card" }, { value: "bank_transfer", label: "Bank Transfer" }, { value: "other", label: "Other" }];

export default function FinanceTransactions({ transactions, services }: { transactions: FinanceTransaction[]; services: ServiceRecord[] }) {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [method, setMethod] = useState("all"); const [status, setStatus] = useState("all"); const [service, setService] = useState("all"); const [type, setType] = useState("all");
  const filtered = useMemo(() => transactions.filter((item) => { const key = dateKey(new Date(item.paid_at)); return (!from || key >= from) && (!to || key <= to) && (method === "all" || item.payment_method === method) && (status === "all" || item.status === status) && (service === "all" || item.service_id === service) && (type === "all" || item.transaction_type === type); }), [from, method, service, status, to, transactions, type]);
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-admin-display text-3xl uppercase text-foreground">Transactions</h2><p className="mt-2 text-sm text-foreground-muted">Complete payment and refund ledger.</p></div><button type="button" onClick={() => downloadTransactionsCsv(filtered)} className="inline-flex min-h-11 items-center justify-center gap-2 border border-border px-5 text-xs uppercase tracking-[0.17em] text-foreground-secondary hover:text-accent"><Download size={15}/>Export CSV</button></div>
    <div className="grid gap-4 border border-border bg-surface p-4 sm:grid-cols-2 xl:grid-cols-6"><DateTimePicker mode="date" label="From" value={from} onChange={setFrom} placeholder="Any date"/><DateTimePicker mode="date" label="To" value={to} onChange={setTo} placeholder="Any date"/><AdminSelect label="Method" value={method} onChange={setMethod} options={METHODS}/><AdminSelect label="Status" value={status} onChange={setStatus} options={[{value:"all",label:"All Statuses"},{value:"completed",label:"Completed"},{value:"pending",label:"Pending"},{value:"failed",label:"Failed"},{value:"voided",label:"Voided"}]}/><AdminSelect label="Service" value={service} onChange={setService} searchable options={[{value:"all",label:"All Services"},...services.map((item)=>({value:item.id,label:item.name}))]}/><AdminSelect label="Type" value={type} onChange={setType} options={[{value:"all",label:"All Types"},{value:"payment",label:"Payments"},{value:"refund",label:"Refunds"}]}/></div>
    <article className="overflow-hidden border border-border bg-surface"><div className="border-b border-border p-4 sm:p-5"><p className="text-sm text-foreground-muted">{filtered.length} matching records</p></div><div className="grid gap-3 p-3 md:hidden">{filtered.map((item)=><article key={item.id} className="min-w-0 border border-border bg-background/30 p-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs uppercase tracking-[.14em] text-accent">{item.booking_reference}</p><p className="mt-2 break-words text-sm text-foreground">{item.customer_name}</p><p className="mt-1 break-words text-xs text-foreground-muted">{item.service_name} · {displayDate(item.paid_at)}</p></div><strong className={`shrink-0 text-sm ${item.transaction_type === "refund" ? "text-rose-300" : "text-emerald-300"}`}>{item.transaction_type === "refund" ? "−" : "+"}{formatMoney(item.amount)}</strong></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 border-t border-border pt-3 text-[10px] uppercase tracking-[.12em] text-foreground-muted"><span>{item.payment_method.replaceAll("_", " ")}</span><span>{item.transaction_type}</span><span>{item.status}</span><span>{item.appointment_status}</span></div></article>)}{!filtered.length?<p className="p-6 text-center text-sm text-foreground-muted">No finance transactions match these filters.</p>:null}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left"><thead className="text-[10px] uppercase tracking-[0.16em] text-foreground-muted"><tr>{["Date","Reference","Customer","Service","Type","Amount","Method","Status","Appointment"].map((head)=><th key={head} className="px-4 py-3 font-normal">{head}</th>)}</tr></thead><tbody>{filtered.map((item)=><tr key={item.id} className="border-t border-border/70 text-sm text-foreground-secondary"><td className="px-4 py-4">{displayDate(item.paid_at)}</td><td className="px-4 py-4 text-foreground">{item.booking_reference}</td><td className="px-4 py-4">{item.customer_name}</td><td className="px-4 py-4">{item.service_name}</td><td className="px-4 py-4 uppercase">{item.transaction_type}</td><td className={item.transaction_type === "refund" ? "px-4 py-4 text-rose-300" : "px-4 py-4 text-emerald-300"}>{item.transaction_type === "refund" ? "−" : "+"}{formatMoney(item.amount)}</td><td className="px-4 py-4 uppercase">{item.payment_method.replaceAll("_", " ")}</td><td className="px-4 py-4 uppercase">{item.status}</td><td className="px-4 py-4 uppercase">{item.appointment_status}</td></tr>)}</tbody></table>{!filtered.length?<p className="p-10 text-center text-sm text-foreground-muted">No finance transactions match these filters.</p>:null}</div></article>
  </div>;
}
