"use client";

/* eslint-disable react/no-unescaped-entities */

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CalendarDays, CreditCard, Megaphone, Plus, Receipt, Scissors } from "lucide-react";
import { ComparisonLine } from "@/components/admin/finance/FinanceOverview";
import type { AdminAppointmentDetail } from "@/lib/appointments/types";
import type { FinanceComparison } from "@/lib/finance/comparison";
import type { FinanceAppointment, FinanceTransaction } from "@/lib/finance/types";
import type { ReceiptRecord } from "@/lib/receipts/types";
import type { AvailableSlotDisplay } from "@/lib/public/available-slots";
import type { ServiceRecord } from "@/lib/services/types";

type Props={today:string;now:string;todayAppointments:AdminAppointmentDetail[];tomorrowAppointments:AdminAppointmentDetail[];availableSlots:AvailableSlotDisplay[];availabilityService:ServiceRecord|null;todayComparison:FinanceComparison;monthComparison:FinanceComparison;sevenDayComparison:FinanceComparison;thirtyDayComparison:FinanceComparison;finance:{transactions:FinanceTransaction[];appointments:FinanceAppointment[];receipts:ReceiptRecord[]}};
const money=(value:number)=>new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF"}).format(value);
const time=(value:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Zurich",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
const zurichDateKey=(value:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Zurich",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
const fullDate=(value:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Zurich",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(value));
const duration=(start:string,end:string)=>`${Math.max(0,Math.round((new Date(end).getTime()-new Date(start).getTime())/60000))} min`;

export default function AdminDashboardView(props:Props){
  const [trendRange,setTrendRange]=useState<"7"|"30">("7");
  const trend=trendRange==="7"?props.sevenDayComparison:props.thirtyDayComparison;
  const nowMs=new Date(props.now).getTime();
  const active=props.todayAppointments.filter((item)=>!['cancelled','no_show'].includes(item.status));
  const next=active.find((item)=>new Date(item.end_at).getTime()>=nowMs)??null;
  const financeByAppointment=new Map(props.finance.appointments.map((item)=>[item.appointmentId,item]));
  const month=props.monthComparison.current.totals;
  const topService=props.monthComparison.servicePerformance[0]?.service??"No data";
  const outstanding=props.finance.appointments.filter((item)=>item.amountDue>item.netPaid);
  const outstandingTotal=outstanding.reduce((sum,item)=>sum+Math.max(0,item.amountDue-item.netPaid),0);
  const unsentReceipts=props.finance.receipts.filter((item)=>!item.emailed_at);
  const activities=buildActivity(props).slice(0,8);
  const kpis=[{label:"Today's Appointments",value:String(active.length).padStart(2,"0"),detail:fullDate(props.now)},{label:"Today's Revenue",value:money(props.todayComparison.current.totals.netRevenue),detail:deltaLabel(props.todayComparison.changes.netRevenue)},{label:"Next Appointment",value:next?time(next.start_at):"—",detail:next?`${next.customer_name} · ${next.service_name}`:"No upcoming appointment"},{label:"Available Slots",value:String(props.availableSlots.length).padStart(2,"0"),detail:props.availabilityService?`For ${props.availabilityService.name}`:"No active service"}];
  return <section className="space-y-7">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.34em] text-foreground-secondary">Dashboard</p><h1 className="mt-4 font-admin-display text-[clamp(2.2rem,5vw,4.25rem)] font-semibold uppercase leading-[.95] tracking-[-.04em] text-foreground">Good Day</h1><p className="mt-3 text-sm text-foreground-secondary">{fullDate(props.now)} · Europe/Zurich</p></div><Link href="/admin/appointments?new=1" className="inline-flex min-h-12 items-center justify-center gap-2 bg-accent px-5 text-xs uppercase tracking-[.18em] text-background"><Plus size={16}/>New Appointment</Link></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map((item)=><article key={item.label} className="border border-border bg-surface p-5"><p className="text-[10px] uppercase tracking-[.19em] text-foreground-muted">{item.label}</p><p className="mt-3 font-admin-display text-3xl tracking-[-.04em] text-foreground">{item.value}</p><p className="mt-2 truncate text-xs text-foreground-secondary">{item.detail}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-12">
      <Schedule appointments={props.todayAppointments} financeByAppointment={financeByAppointment} nextId={next?.id??null} nowMs={nowMs} slots={props.availableSlots}/>
      <aside className="order-5 border border-border bg-surface p-5 xl:order-2 xl:col-span-4"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Business Snapshot</p><h2 className="mt-2 font-admin-display text-2xl uppercase text-foreground">This Month</h2></div><Link href="/admin/finance" className="text-xs uppercase tracking-[.13em] text-accent">View Finance →</Link></div><dl className="mt-5 divide-y divide-border">{[["Net revenue",money(month.netRevenue)],["Completed appointments",String(month.completedAppointments)],["Average ticket",money(month.averageTicket)],["Discounts",money(month.discounts)],["Top service",topService]].map(([label,value])=><div key={label} className="flex items-center justify-between gap-4 py-3"><dt className="text-xs text-foreground-muted">{label}</dt><dd className="text-right text-sm text-foreground">{value}</dd></div>)}</dl></aside>
      <section className="order-4 border border-border bg-surface p-4 sm:p-5 xl:order-3 xl:col-span-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Revenue Performance</p><p className="mt-1 text-sm text-foreground-secondary">Net revenue against the previous equivalent period.</p></div><div className="flex border border-border">{(["7","30"] as const).map((value)=><button key={value} onClick={()=>setTrendRange(value)} className={`min-h-9 px-4 text-[10px] uppercase tracking-[.14em] ${trendRange===value?"bg-accent text-background":"text-foreground-muted"}`}>{value} Days</button>)}</div></div><ComparisonLine current={trend.current.series} previous={trend.previous.series} metric="revenue" formatValue={money} periodLabels={[`Current ${trendRange} days`,`Previous ${trendRange} days`]}/></section>
      <Attention outstandingCount={outstanding.length} outstandingTotal={outstandingTotal} unsentReceipts={unsentReceipts.length} tomorrowBookings={props.tomorrowAppointments.filter((item)=>item.status==="confirmed").length}/>
      <QuickActions/>
      <section className="order-6 border border-border bg-surface p-5 xl:col-span-6"><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Recent Activity</p><div className="mt-4 divide-y divide-border">{activities.map((item,index)=><div key={`${item.at}-${index}`} className="py-3"><p className="text-sm text-foreground">{item.label}</p><p className="mt-1 text-xs text-foreground-muted">{item.context} · {fullDate(item.at)} {time(item.at)}</p></div>)}{!activities.length?<p className="py-8 text-center text-sm text-foreground-muted">No recent activity.</p>:null}</div></section>
    </div>
  </section>;
}

function Schedule({appointments,financeByAppointment,nextId,nowMs,slots}:{appointments:AdminAppointmentDetail[];financeByAppointment:Map<string,FinanceAppointment>;nextId:string|null;nowMs:number;slots:AvailableSlotDisplay[]}){return <section className="order-1 overflow-hidden border border-border bg-surface xl:col-span-8"><div className="flex items-end justify-between border-b border-border p-5"><div><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Today's Schedule</p><h2 className="mt-2 font-admin-display text-2xl uppercase text-foreground">Appointments</h2></div><Link href="/admin/appointments" className="text-xs uppercase tracking-[.13em] text-accent">View All Appointments →</Link></div><div className="divide-y divide-border">{appointments.map((item)=>{const finance=financeByAppointment.get(item.id);const past=new Date(item.end_at).getTime()<nowMs;return <Link key={item.id} href={`/admin/appointments?view=day&date=${zurichDateKey(item.start_at)}&appointmentId=${item.id}`} className={`grid gap-2 p-4 transition-colors hover:bg-background/50 sm:grid-cols-[70px_minmax(0,1.2fr)_minmax(0,1fr)_70px_90px_auto] sm:items-center ${past?"opacity-45":item.id===nextId?"bg-accent/[.07]":""}`}><strong className="text-lg text-accent">{time(item.start_at)}</strong><span><b className="block text-sm text-foreground">{item.customer_name}</b><small className="text-foreground-muted">{item.booking_type}</small></span><span className="text-sm text-foreground-secondary">{item.service_name}</span><span className="text-xs text-foreground-muted">{duration(item.start_at,item.end_at)}</span><span className="text-sm text-foreground">{money(finance?.amountDue??Number(item.final_price??0))}</span><span className="text-[10px] uppercase tracking-[.12em] text-foreground-muted">{item.status.replaceAll("_"," ")}</span></Link>})}{!appointments.length?<p className="p-10 text-center text-sm text-foreground-muted">No appointments scheduled today.</p>:null}</div>{slots.length?<div className="border-t border-border p-4"><p className="text-[10px] uppercase tracking-[.16em] text-foreground-muted">Open slots</p><div className="mt-3 flex flex-wrap gap-2">{slots.slice(0,8).map((slot)=><span key={slot.slot_start} className="border border-border px-3 py-2 text-xs text-foreground-secondary">{slot.time}</span>)}</div></div>:null}</section>}
function Attention({outstandingCount,outstandingTotal,unsentReceipts,tomorrowBookings}:{outstandingCount:number;outstandingTotal:number;unsentReceipts:number;tomorrowBookings:number}){const items=[outstandingCount?{text:`${outstandingCount} appointment${outstandingCount===1?" has":"s have"} outstanding payments`,detail:`${money(outstandingTotal)} outstanding`,href:"/admin/finance",action:"Review"}:null,unsentReceipts?{text:`${unsentReceipts} receipt${unsentReceipts===1?" has":"s have"} not been emailed`,detail:"Customer delivery pending",href:"/admin/finance/receipts",action:"Review"}:null,tomorrowBookings>0&&tomorrowBookings<3?{text:`Tomorrow has only ${tomorrowBookings} booking${tomorrowBookings===1?"":"s"}`,detail:"Review upcoming availability",href:"/admin/calendar",action:"Calendar"}:null].filter(Boolean) as Array<{text:string;detail:string;href:string;action:string}>;return <aside className="order-2 border border-border bg-surface p-5 xl:order-4 xl:col-span-4"><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Needs Attention</p><div className="mt-4 divide-y divide-border">{items.map((item)=><div key={item.text} className="py-4"><p className="text-sm text-foreground">{item.text}</p><p className="mt-1 text-xs text-foreground-muted">{item.detail}</p><Link href={item.href} className="mt-3 inline-flex text-[10px] uppercase tracking-[.15em] text-accent">{item.action} →</Link></div>)}{!items.length?<p className="py-8 text-sm text-emerald-300">Everything is up to date.</p>:null}</div></aside>}
function QuickActions(){const items=[{label:"New Appointment",href:"/admin/appointments?new=1",icon:Plus},{label:"Record Payment",href:"/admin/appointments",icon:CreditCard},{label:"Add Closure",href:"/admin/site-settings/business-hours",icon:CalendarDays},{label:"Generate Report",href:"/admin/finance/reports",icon:Receipt},{label:"Create Announcement",href:"/admin/site-settings/announcements",icon:Megaphone},{label:"Manage Services",href:"/admin/site-settings/services",icon:Scissors}];return <section className="order-3 border border-border bg-surface p-5 xl:order-5 xl:col-span-6"><p className="text-xs uppercase tracking-[.2em] text-foreground-muted">Quick Actions</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{items.map(({label,href,icon:Icon})=><Link key={label} href={href} className="flex min-h-12 items-center justify-between border border-border px-4 text-xs uppercase tracking-[.12em] text-foreground-secondary transition-colors hover:border-accent/50 hover:text-accent"><span className="flex items-center gap-3"><Icon size={15}/>{label}</span><ArrowRight size={14}/></Link>)}</div></section>}
function deltaLabel(value:number|null){if(value===null)return "No previous-day baseline";return `${value>=0?"↑":"↓"} ${Math.abs(value).toFixed(1)}% vs yesterday`}
function buildActivity(props:Props){const events:Array<{at:string;label:string;context:string}>=[];props.finance.transactions.forEach((item)=>events.push({at:item.paid_at,label:item.transaction_type==="refund"?"Refund recorded":"Payment received",context:`${item.customer_name} · ${money(item.amount)}`}));props.todayAppointments.forEach((item)=>events.push({at:item.updated_at,label:item.status==="cancelled"?"Appointment cancelled":item.status==="completed"?"Appointment completed":"Appointment booked",context:`${item.customer_name} · ${item.service_name}`}));props.finance.receipts.forEach((item)=>events.push({at:item.emailed_at??item.issued_at,label:item.emailed_at?"Receipt emailed":"Receipt issued",context:`Beleg ${item.receipt_number} · ${item.customer_name??"Customer"}`}));return events.sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime())}
