"use client";

import { useState, useTransition, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { AtSign, MapPin, PenLine, Phone } from "lucide-react";
import ContactSection from "@/components/home/ContactSection";
import { saveContactSectionSettings } from "@/app/admin/(dashboard)/site-settings/contact/actions";
import type { ContactSectionSettings } from "@/lib/contact-section/types";

type Props = { initialSettings: ContactSectionSettings; initialError?: string };

function Toggle({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className="flex min-h-12 w-full items-center justify-between gap-5 border-y border-border py-3 text-left"><span><span className="block text-sm text-foreground">{label}</span>{description ? <span className="mt-1 block text-xs leading-5 text-foreground-muted">{description}</span> : null}</span><span className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? "bg-accent" : "bg-surface-elevated"}`}><span className={`absolute top-1 size-4 rounded-full bg-background transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /></span></button>;
}

function Field({ label, value, onChange, placeholder, multiline = false, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean; type?: string }) {
  return <label className="block min-w-0"><span className="text-[10px] uppercase tracking-[.16em] text-foreground-muted">{label}</span>{multiline ? <textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full resize-y border border-border bg-background px-4 py-3 text-base leading-6 text-foreground outline-none placeholder:text-foreground-muted focus:border-accent sm:text-sm"/> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 min-h-12 w-full border border-border bg-background px-4 text-base text-foreground outline-none placeholder:text-foreground-muted focus:border-accent sm:text-sm"/>}</label>;
}

function ConfigSection({ icon, title, description, children }: { icon: ReactNode; title: string; description: string; children: ReactNode }) {
  return <section className="border border-border bg-surface p-4 sm:p-6"><div className="flex items-start gap-4 border-b border-border pb-4"><span className="flex size-10 shrink-0 items-center justify-center border border-border text-accent" aria-hidden="true">{icon}</span><div className="min-w-0"><h3 className="font-admin-display text-xl font-semibold text-foreground">{title}</h3><p className="mt-1 text-xs leading-5 text-foreground-muted">{description}</p></div></div><div className="mt-5">{children}</div></section>;
}

export default function ContactSettingsManager({ initialSettings, initialError = "" }: Props) {
  const router = useRouter();
  const [settings, setSettings] = useState(initialSettings);
  const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(initialError ? { kind: "error", text: initialError } : null);
  const [isPending, startTransition] = useTransition();
  const update = <K extends keyof ContactSectionSettings>(key: K, value: ContactSectionSettings[K]) => { setSettings((current) => ({ ...current, [key]: value })); setFeedback(null); };
  const save = () => startTransition(async () => { const result = await saveContactSectionSettings(settings); setFeedback({ kind: result.success ? "success" : "error", text: result.message }); if (result.success) router.refresh(); });

  return <section className="min-w-0"><div className="border-b border-border pb-5"><h2 className="font-admin-display text-2xl font-semibold text-foreground sm:text-3xl">Contact</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-foreground-secondary">Manage the compact public contact actions and their labels.</p></div>{feedback ? <div role="status" className={`mt-5 border px-4 py-3 text-sm ${feedback.kind === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-200" : "border-rose-500/30 bg-rose-500/10 text-rose-200"}`}>{feedback.text}</div> : null}<div className="mt-6 grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(420px,.9fr)]"><div className="min-w-0 space-y-6"><section className="border border-border bg-surface p-4 sm:p-6"><div className="border-b border-border pb-4"><h3 className="font-admin-display text-xl font-semibold text-foreground">Contact Section</h3><p className="mt-1 text-xs leading-5 text-foreground-muted">Control the compact section heading and public visibility.</p></div><div className="mt-5"><Toggle label="Contact section enabled" description="Hide the entire public Contact section when disabled." checked={settings.isEnabled} onChange={(value) => update("isEnabled", value)}/></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Eyebrow" value={settings.eyebrow} onChange={(value) => update("eyebrow", value)} placeholder="Contact"/><Field label="Title" value={settings.title} onChange={(value) => update("title", value)} placeholder="Connect with 1200."/></div></section>
          <ConfigSection icon={<Phone size={18}/>} title="Phone" description="Configure the call action and its customer-facing label."><div className="grid gap-5 sm:grid-cols-2"><Field label="Phone Number" type="tel" value={settings.phoneNumber} onChange={(value) => update("phoneNumber", value)} placeholder="+41... (Optional)"/><Field label="Display Number" value={settings.phoneDisplay} onChange={(value) => update("phoneDisplay", value)} placeholder="Displayed number (Optional)"/><div className="sm:col-span-2"><Field label="CTA Label" value={settings.callCtaLabel} onChange={(value) => update("callCtaLabel", value)} placeholder="Call"/></div></div></ConfigSection>
          <ConfigSection icon={<AtSign size={18}/>} title="Instagram" description="Show or hide the Instagram action independently."><Toggle label="Instagram enabled" checked={settings.instagramEnabled} onChange={(value) => update("instagramEnabled", value)}/>{settings.instagramEnabled ? <div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Username" value={settings.instagramUsername} onChange={(value) => update("instagramUsername", value)} placeholder="@username (Optional)"/><Field label="Instagram URL" type="url" value={settings.instagramUrl} onChange={(value) => update("instagramUrl", value)} placeholder="https://instagram.com/..."/><div className="sm:col-span-2"><Field label="CTA Label" value={settings.instagramCtaLabel} onChange={(value) => update("instagramCtaLabel", value)} placeholder="Instagram"/></div></div> : null}</ConfigSection>
          <ConfigSection icon={<PenLine size={18}/>} title="Leave a Review" description="Configure the direct Google review-writing action."><Toggle label="Leave a Review enabled" checked={settings.googleReviewsEnabled} onChange={(value) => update("googleReviewsEnabled", value)}/>{settings.googleReviewsEnabled ? <div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Leave-review URL" type="url" value={settings.googleLeaveReviewUrl} onChange={(value) => update("googleLeaveReviewUrl", value)} placeholder="https://g.page/..."/><Field label="CTA Label" value={settings.leaveReviewCtaLabel} onChange={(value) => update("leaveReviewCtaLabel", value)} placeholder="Leave Review"/></div> : null}</ConfigSection>
          <details className="border border-border bg-surface"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 px-4 text-[10px] uppercase tracking-[.18em] text-foreground-secondary outline-none focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-accent sm:px-6"><span>Advanced / Legacy Content</span><span className="text-accent">+</span></summary><div className="border-t border-border p-4 sm:p-6"><div className="flex items-start gap-4"><MapPin size={18} className="mt-0.5 shrink-0 text-accent" aria-hidden="true"/><p className="text-xs leading-5 text-foreground-muted">These values remain available for compatibility. Visit Studio continues to own the public address, directions, and map presentation.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Description" value={settings.description} onChange={(value) => update("description", value)} placeholder="Description (Optional)" multiline/></div><Field label="Address" value={settings.address} onChange={(value) => update("address", value)} placeholder="Studio address (Optional)"/><Field label="Map URL" type="url" value={settings.mapUrl} onChange={(value) => update("mapUrl", value)} placeholder="https://maps.google.com/... (Optional)"/></div></div></details>
          <div className="sticky bottom-0 z-10 flex flex-col-reverse gap-3 border-t border-border bg-background/95 py-4 pb-[max(16px,env(safe-area-inset-bottom))] backdrop-blur sm:flex-row sm:justify-end"><button type="button" onClick={() => { setSettings(initialSettings); setFeedback(null); }} disabled={isPending} className="min-h-12 border border-border px-5 text-[10px] uppercase tracking-[.16em] text-foreground-secondary disabled:opacity-50">Reset</button><button type="button" onClick={save} disabled={isPending} className="min-h-12 bg-accent px-7 text-[10px] font-semibold uppercase tracking-[.18em] text-background disabled:opacity-50">{isPending ? "Saving..." : "Save Contact Settings"}</button></div>
        </div><aside className="min-w-0 xl:sticky xl:top-6 xl:self-start"><p className="mb-3 text-[10px] uppercase tracking-[.18em] text-foreground-muted">Live Public Preview</p><div className="min-w-0 overflow-hidden border border-border bg-background"><ContactSection settings={settings} preview/></div></aside></div></section>;
}
