"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import ContactSection from "@/components/home/ContactSection";
import { saveContactSectionSettings } from "@/app/admin/(dashboard)/site-settings/contact/actions";
import type { ContactSectionSettings } from "@/lib/contact-section/types";

type Props = { initialSettings: ContactSectionSettings; initialError?: string };

function Toggle({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className="flex min-h-12 w-full items-center justify-between gap-5 border-y border-border py-3 text-left"><span><span className="block text-sm text-foreground">{label}</span>{description ? <span className="mt-1 block text-xs leading-5 text-foreground-muted">{description}</span> : null}</span><span className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? "bg-accent" : "bg-surface-elevated"}`}><span className={`absolute top-1 size-4 rounded-full bg-background transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /></span></button>;
}

function Field({ label, value, onChange, placeholder, multiline = false, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean; type?: string }) {
  return <label className="block min-w-0"><span className="text-[10px] uppercase tracking-[.16em] text-foreground-muted">{label}</span>{multiline ? <textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full resize-y border border-border bg-background px-4 py-3 text-base leading-6 text-foreground outline-none placeholder:text-foreground-muted focus:border-accent sm:text-sm"/> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 min-h-12 w-full border border-border bg-background px-4 text-base text-foreground outline-none placeholder:text-foreground-muted focus:border-accent sm:text-sm"/>}</label>;
}

function SectionHeading({ title, description }: { title: string; description: string }) {
  return <div className="border-b border-border pb-4"><h3 className="font-admin-display text-xl font-semibold text-foreground">{title}</h3><p className="mt-1 text-xs leading-5 text-foreground-muted">{description}</p></div>;
}

export default function ContactSettingsManager({ initialSettings, initialError = "" }: Props) {
  const router = useRouter();
  const [settings, setSettings] = useState(initialSettings);
  const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(initialError ? { kind: "error", text: initialError } : null);
  const [isPending, startTransition] = useTransition();
  const update = <K extends keyof ContactSectionSettings>(key: K, value: ContactSectionSettings[K]) => { setSettings((current) => ({ ...current, [key]: value })); setFeedback(null); };
  const save = () => startTransition(async () => { const result = await saveContactSectionSettings(settings); setFeedback({ kind: result.success ? "success" : "error", text: result.message }); if (result.success) router.refresh(); });

  return <section className="min-w-0"><div className="border-b border-border pb-5"><h2 className="font-admin-display text-2xl font-semibold text-foreground sm:text-3xl">Contact</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-foreground-secondary">Manage the public studio contact section, social links, and review actions.</p></div>{feedback ? <div role="status" className={`mt-5 border px-4 py-3 text-sm ${feedback.kind === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-200" : "border-rose-500/30 bg-rose-500/10 text-rose-200"}`}>{feedback.text}</div> : null}<div className="mt-6 grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(420px,.9fr)]"><div className="min-w-0 space-y-7"><section className="border border-border bg-surface p-4 sm:p-6"><SectionHeading title="General" description="Control the section heading, description, studio location, and visibility."/><div className="mt-5"><Toggle label="Contact section enabled" description="Hide the entire public section when disabled." checked={settings.isEnabled} onChange={(value) => update("isEnabled", value)}/></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Eyebrow" value={settings.eyebrow} onChange={(value) => update("eyebrow", value)} placeholder="Contact label (Optional)"/><Field label="Title" value={settings.title} onChange={(value) => update("title", value)} placeholder="Contact title (Optional)"/><div className="sm:col-span-2"><Field label="Description" value={settings.description} onChange={(value) => update("description", value)} placeholder="Section description (Optional)" multiline/></div><Field label="Address" value={settings.address} onChange={(value) => update("address", value)} placeholder="Studio address (Optional)"/><Field label="Map URL" type="url" value={settings.mapUrl} onChange={(value) => update("mapUrl", value)} placeholder="https://maps.google.com/... (Optional)"/></div></section>
          <section className="border border-border bg-surface p-4 sm:p-6"><SectionHeading title="Phone" description="The dialing value and customer-facing display may be formatted separately."/><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Phone Number" type="tel" value={settings.phoneNumber} onChange={(value) => update("phoneNumber", value)} placeholder="+41... (Optional)"/><Field label="Display Phone Number" value={settings.phoneDisplay} onChange={(value) => update("phoneDisplay", value)} placeholder="Displayed phone number (Optional)"/></div></section>
          <section className="border border-border bg-surface p-4 sm:p-6"><SectionHeading title="Instagram" description="Show or hide the Instagram contact block independently."/><div className="mt-5"><Toggle label="Instagram enabled" checked={settings.instagramEnabled} onChange={(value) => update("instagramEnabled", value)}/></div>{settings.instagramEnabled ? <div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Username" value={settings.instagramUsername} onChange={(value) => update("instagramUsername", value)} placeholder="@username (Optional)"/><Field label="Profile URL" type="url" value={settings.instagramUrl} onChange={(value) => update("instagramUrl", value)} placeholder="https://instagram.com/... (Optional)"/></div> : null}</section>
          <section className="border border-border bg-surface p-4 sm:p-6"><SectionHeading title="Google Reviews" description="Link customers to existing Google review pages without API-derived ratings."/><div className="mt-5"><Toggle label="Google Reviews enabled" checked={settings.googleReviewsEnabled} onChange={(value) => update("googleReviewsEnabled", value)}/></div>{settings.googleReviewsEnabled ? <div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Read Reviews URL" type="url" value={settings.googleReviewsUrl} onChange={(value) => update("googleReviewsUrl", value)} placeholder="https://google.com/... (Optional)"/><Field label="Leave A Review URL" type="url" value={settings.googleLeaveReviewUrl} onChange={(value) => update("googleLeaveReviewUrl", value)} placeholder="https://g.page/... (Optional)"/></div> : null}</section>
          <section className="border border-border bg-surface p-4 sm:p-6"><SectionHeading title="CTA Labels" description="Leave a label empty to hide its corresponding action."/><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Call Now" value={settings.callCtaLabel} onChange={(value) => update("callCtaLabel", value)} placeholder="Call CTA label (Optional)"/><Field label="Open Instagram" value={settings.instagramCtaLabel} onChange={(value) => update("instagramCtaLabel", value)} placeholder="Instagram CTA label (Optional)"/><Field label="Read Reviews" value={settings.reviewsCtaLabel} onChange={(value) => update("reviewsCtaLabel", value)} placeholder="Reviews CTA label (Optional)"/><Field label="Leave A Review" value={settings.leaveReviewCtaLabel} onChange={(value) => update("leaveReviewCtaLabel", value)} placeholder="Leave-review CTA label (Optional)"/></div></section>
          <div className="sticky bottom-0 z-10 flex flex-col-reverse gap-3 border-t border-border bg-background/95 py-4 pb-[max(16px,env(safe-area-inset-bottom))] backdrop-blur sm:flex-row sm:justify-end"><button type="button" onClick={() => { setSettings(initialSettings); setFeedback(null); }} disabled={isPending} className="min-h-12 border border-border px-5 text-[10px] uppercase tracking-[.16em] text-foreground-secondary disabled:opacity-50">Reset</button><button type="button" onClick={save} disabled={isPending} className="min-h-12 bg-accent px-7 text-[10px] font-semibold uppercase tracking-[.18em] text-background disabled:opacity-50">{isPending ? "Saving..." : "Save Contact Settings"}</button></div>
        </div><aside className="min-w-0 xl:sticky xl:top-6 xl:self-start"><p className="mb-3 text-[10px] uppercase tracking-[.18em] text-foreground-muted">Live Public Preview</p><div className="min-w-0 overflow-hidden border border-border bg-background"><ContactSection settings={settings} preview/></div></aside></div></section>;
}
